FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY ./Mongodb/ /app/Mongodb/
COPY ./agents/ /app/agents/
COPY ./azure_clients/ /app/azure_clients/
COPY ./pages/ /app/pages/
COPY ./services/ /app/services/
COPY ./utils/ /app/utils/
COPY main.py /app/main.py
COPY ./assets/ /app/assets/
COPY ./config/ /app/config/

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port", "8501", "--server.address", "0.0.0.0"]