FROM python:3.12-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY ./Mongodb/ /app/Mongodb/
COPY ./fastapi_chatapp.py /app/fastapi_chatapp.py
COPY ./utils/ /app/utils/
COPY ./azure_clients/title_azure_client.py /app/azure_clients/
COPY ./config/ /app/config/

EXPOSE 8001

CMD ["uvicorn", "fastapi_chatapp:app", "--host", "0.0.0.0", "--port", "8001"]