import { Link } from "react-router-dom";
import {
  MessageSquare,
  BookOpen,
  BarChart3,
  FileSearch,
  ArrowRight,
  Cpu,
} from "lucide-react";
import AppShell from "../components/AppShell.jsx";
import { Card } from "../components/ui.jsx";
import { useApp } from "../context/AppContext.jsx";

const CARDS = [
  {
    to: "/chat",
    title: "Chatbot",
    desc: "Interact with the intelligent multi-agent chatbot system.",
    icon: MessageSquare,
    accent: "from-brand-500 to-brand-700",
    cta: "Launch Chatbot",
  },
  {
    to: "/knowledge",
    title: "Knowledge Management",
    desc: "Parse documents, generate embeddings, and manage your knowledge base.",
    icon: BookOpen,
    accent: "from-emerald-500 to-emerald-700",
    cta: "Launch Knowledge Management",
  },
  {
    to: "/rag-eval",
    title: "RAG Evaluation",
    desc: "Evaluate and monitor your RAG pipeline performance.",
    icon: BarChart3,
    accent: "from-violet-500 to-violet-700",
    cta: "Launch RAG Evaluation",
  },
];

export default function Dashboard() {
  const { user } = useApp();
  return (
    <AppShell>
      <div className="mb-8">
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">
          Welcome back, {user?.username} 
        </h1>
        <p className="mt-1.5 text-slate-500">
          Your multi-agent workspace. Pick a tool to get started.
        </p>
      </div>

      {/* Tool cards */}
      <div className="grid gap-5 md:grid-cols-3">
        {CARDS.map((c) => (
          <Link key={c.to} to={c.to} className="group">
            <Card className="flex h-full flex-col p-6 transition-all hover:-translate-y-0.5 hover:shadow-soft">
              <div
                className={`mb-5 grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br ${c.accent} text-white shadow-soft`}
              >
                <c.icon size={22} />
              </div>
              <h3 className="text-lg font-bold text-slate-900">{c.title}</h3>
              <p className="mt-1.5 flex-1 text-sm text-slate-500">{c.desc}</p>
              <div className="mt-5 flex items-center gap-1.5 text-sm font-semibold text-brand-600">
                {c.cta}
                <ArrowRight
                  size={16}
                  className="transition-transform group-hover:translate-x-1"
                />
              </div>
            </Card>
          </Link>
        ))}
      </div>

      {/* Secondary tools */}
      <div className="mt-8">
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-400">
          More tools
        </h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <Link to="/parser" className="group">
            <Card className="flex items-center gap-4 p-5 transition hover:shadow-soft">
              <div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-amber-600">
                <FileSearch size={20} />
              </div>
              <div className="flex-1">
                <div className="font-semibold text-slate-900">Document Parser</div>
                <div className="text-sm text-slate-500">
                  Parse files &amp; URLs, chunk, embed and store.
                </div>
              </div>
              <ArrowRight
                size={18}
                className="text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-brand-600"
              />
            </Card>
          </Link>
          <Link to="/workspace" className="group">
            <Card className="flex items-center gap-4 p-5 transition hover:shadow-soft">
              <div className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-600">
                <Cpu size={20} />
              </div>
              <div className="flex-1">
                <div className="font-semibold text-slate-900">
                  Workspace Explorer
                </div>
                <div className="text-sm text-slate-500">
                  Browse files generated by the Coder agent.
                </div>
              </div>
              <ArrowRight
                size={18}
                className="text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-brand-600"
              />
            </Card>
          </Link>
        </div>
      </div>
    </AppShell>
  );
}
